"""
Smart Multi-Document Compliance & Contract Auditor
===================================================

Professional Streamlit frontend redesign.

Backend pipeline preserved:
PDF -> extraction -> chunking -> embeddings -> FAISS
-> retrieval -> Groq answer generation
-> Corrective RAG validation -> cited answer

Only the UI/UX presentation layer has been redesigned.
"""

import html
import io
import logging
import time
from dataclasses import dataclass, field
from typing import List, Tuple

import numpy as np
import streamlit as st
from pypdf import PdfReader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# --------------------------------------------------------------------------
# Heavy dependencies
# --------------------------------------------------------------------------

try:
    import faiss
except ImportError as e:
    raise ImportError(
        "faiss-cpu is not installed. Run: pip install faiss-cpu"
    ) from e

try:
    from sentence_transformers import SentenceTransformer
except ImportError as e:
    raise ImportError(
        "sentence-transformers is not installed. "
        "Run: pip install sentence-transformers"
    ) from e

from groq import Groq


# --------------------------------------------------------------------------
# Logging
# --------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)

logger = logging.getLogger("contract_auditor")


# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"
GROQ_MODEL_NAME = "openai/gpt-oss-120b"

CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
TOP_K_RESULTS = 5


# --------------------------------------------------------------------------
# Prompts
# --------------------------------------------------------------------------

SYSTEM_ANSWER_PROMPT = """You are a precise contract and compliance analysis assistant.

You must answer the user's question using ONLY the information contained in
the provided context chunks below. Each chunk is labeled with its source
document and page number.

Rules:
- Do NOT use any outside knowledge or assumptions.
- If the answer is not fully contained in the context, explicitly say what is
  missing rather than guessing.
- When you state a fact, mention which document/page it came from
  (e.g., "According to Vendor_Agreement.pdf, page 4...").
- Be concise and structured.
- Use bullet points for multiple clauses/terms.
"""


SYSTEM_VALIDATION_PROMPT = """You are a strict fact-checking auditor.

You will be given:
1. A set of source context chunks with document/page labels
2. A question
3. A draft answer generated by another AI from that context

Your job is to verify the draft answer against the context ONLY.

Respond in this exact format:

VERDICT: SUPPORTED | PARTIALLY_SUPPORTED | NOT_SUPPORTED | NOT_IN_DOCUMENT
MISSING_OR_INCORRECT: <list any claims in the answer that are not backed by
the context, or state "None" if the answer is fully grounded>
NOTE: <one short sentence summarizing your finding for the end user>

Verdict definitions:

SUPPORTED:
Every factual claim in the answer is explicitly backed by the context.

PARTIALLY_SUPPORTED:
Some claims are backed, others are not.

NOT_SUPPORTED:
The answer states a clause, number, date, or obligation that does NOT appear
in the context. This is the category for genuinely fabricated content.

NOT_IN_DOCUMENT:
The context simply does not address the topic asked about, and the answer
correctly says so instead of inventing an answer. This is a GOOD outcome, not
a hallucination.

Be strict.

Only use NOT_SUPPORTED when the answer asserts something as fact that
contradicts or is absent from the context.

An honest "not found" answer should be NOT_IN_DOCUMENT, never NOT_SUPPORTED.
"""


# --------------------------------------------------------------------------
# Data structures
# --------------------------------------------------------------------------

@dataclass
class Chunk:
    """A single retrievable unit of text with citation metadata."""

    text: str
    source_file: str
    page_number: int
    chunk_id: int


@dataclass
class VectorStore:
    """In-memory FAISS index paired with chunk metadata."""

    index: "faiss.IndexFlatL2" = None
    chunks: List[Chunk] = field(default_factory=list)
    dimension: int = 0

    def is_empty(self) -> bool:
        return self.index is None or len(self.chunks) == 0


# --------------------------------------------------------------------------
# Cached model loader
# --------------------------------------------------------------------------

@st.cache_resource(show_spinner=False)
def load_embedding_model() -> SentenceTransformer:
    logger.info("Loading embedding model: %s", EMBEDDING_MODEL_NAME)
    return SentenceTransformer(EMBEDDING_MODEL_NAME)


# --------------------------------------------------------------------------
# Groq client
# --------------------------------------------------------------------------

def get_groq_client() -> Groq:
    api_key = st.secrets.get("GROQ_API_KEY", None)

    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY not found in Streamlit secrets. "
            "Add it locally to .streamlit/secrets.toml or configure it "
            "in Streamlit Community Cloud."
        )

    return Groq(api_key=api_key)


# --------------------------------------------------------------------------
# PDF extraction
# --------------------------------------------------------------------------

def extract_text_by_page(
    file_bytes: bytes,
    filename: str
) -> List[Tuple[int, str]]:

    pages = []

    try:
        reader = PdfReader(io.BytesIO(file_bytes))

        for i, page in enumerate(reader.pages, start=1):

            try:
                text = page.extract_text() or ""

                if text.strip():
                    pages.append((i, text))
                else:
                    logger.warning(
                        "No extractable text on page %d of %s",
                        i,
                        filename,
                    )

            except Exception as page_err:
                logger.error(
                    "Failed to extract page %d of %s: %s",
                    i,
                    filename,
                    page_err,
                )

    except Exception as e:
        logger.error("Failed to read PDF %s: %s", filename, e)

        raise ValueError(
            f"Could not read '{filename}'. Is it a valid PDF? ({e})"
        ) from e

    return pages


# --------------------------------------------------------------------------
# Chunking
# --------------------------------------------------------------------------

def chunk_documents(uploaded_files) -> List[Chunk]:

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        separators=[
            "\n\n",
            "\n",
            ". ",
            " ",
            "",
        ],
    )

    all_chunks: List[Chunk] = []
    chunk_id_counter = 0

    for uploaded_file in uploaded_files:

        filename = uploaded_file.name

        try:

            file_bytes = uploaded_file.read()

            pages = extract_text_by_page(
                file_bytes,
                filename,
            )

            if not pages:

                st.warning(
                    f"'{filename}' produced no extractable text. "
                    "It may be a scanned/image-only PDF that needs OCR."
                )

                continue

            for page_number, page_text in pages:

                page_chunks = splitter.split_text(page_text)

                for chunk_text in page_chunks:

                    all_chunks.append(
                        Chunk(
                            text=chunk_text,
                            source_file=filename,
                            page_number=page_number,
                            chunk_id=chunk_id_counter,
                        )
                    )

                    chunk_id_counter += 1

        except ValueError as ve:

            st.error(str(ve))

            logger.error(
                "Skipping file %s due to error: %s",
                filename,
                ve,
            )

        except Exception as e:

            st.error(
                f"Unexpected error processing '{filename}': {e}"
            )

            logger.exception(
                "Unexpected error processing %s",
                filename,
            )

    logger.info(
        "Chunked %d total chunks from %d file(s).",
        len(all_chunks),
        len(uploaded_files),
    )

    return all_chunks


# --------------------------------------------------------------------------
# Vector store
# --------------------------------------------------------------------------

def build_vector_store(
    chunks: List[Chunk],
    embedder: SentenceTransformer,
) -> VectorStore:

    if not chunks:
        return VectorStore()

    texts = [c.text for c in chunks]

    logger.info(
        "Embedding %d chunks...",
        len(texts),
    )

    embeddings = embedder.encode(
        texts,
        show_progress_bar=False,
        convert_to_numpy=True,
        normalize_embeddings=True,
    ).astype("float32")

    dimension = embeddings.shape[1]

    index = faiss.IndexFlatL2(dimension)

    index.add(embeddings)

    logger.info(
        "FAISS index built with dimension %d.",
        dimension,
    )

    return VectorStore(
        index=index,
        chunks=chunks,
        dimension=dimension,
    )


# --------------------------------------------------------------------------
# Retrieval
# --------------------------------------------------------------------------

def retrieve_top_chunks(
    query: str,
    store: VectorStore,
    embedder: SentenceTransformer,
    k: int = TOP_K_RESULTS,
) -> List[Chunk]:

    if store.is_empty():
        return []

    query_vec = embedder.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True,
    ).astype("float32")

    k = min(
        k,
        len(store.chunks),
    )

    distances, indices = store.index.search(
        query_vec,
        k,
    )

    results = []

    for idx in indices[0]:

        if 0 <= idx < len(store.chunks):
            results.append(
                store.chunks[idx]
            )

    return results


# --------------------------------------------------------------------------
# Context formatting
# --------------------------------------------------------------------------

def format_context(chunks: List[Chunk]) -> str:

    blocks = []

    for c in chunks:

        blocks.append(
            f"[Source: {c.source_file}, Page {c.page_number}]\n"
            f"{c.text}"
        )

    return "\n\n---\n\n".join(blocks)


# --------------------------------------------------------------------------
# Answer generation
# --------------------------------------------------------------------------

def generate_answer(
    client: Groq,
    question: str,
    context: str,
) -> str:

    try:

        response = client.chat.completions.create(
            model=GROQ_MODEL_NAME,
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_ANSWER_PROMPT,
                },
                {
                    "role": "user",
                    "content": (
                        f"CONTEXT:\n{context}\n\n"
                        f"QUESTION:\n{question}"
                    ),
                },
            ],
            temperature=0.1,
            max_tokens=1024,
        )

        return response.choices[0].message.content.strip()

    except Exception as e:

        logger.exception(
            "Groq answer generation failed"
        )

        raise RuntimeError(
            f"Answer generation failed: {e}"
        ) from e


# --------------------------------------------------------------------------
# Corrective RAG validation
# --------------------------------------------------------------------------

def validate_answer(
    client: Groq,
    question: str,
    context: str,
    draft_answer: str,
) -> str:

    try:

        response = client.chat.completions.create(
            model=GROQ_MODEL_NAME,
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_VALIDATION_PROMPT,
                },
                {
                    "role": "user",
                    "content": (
                        f"CONTEXT:\n{context}\n\n"
                        f"QUESTION:\n{question}\n\n"
                        f"DRAFT ANSWER:\n{draft_answer}"
                    ),
                },
            ],
            temperature=0.0,
            max_tokens=400,
        )

        return response.choices[0].message.content.strip()

    except Exception as e:

        logger.exception(
            "Groq validation call failed"
        )

        return (
            "VERDICT: UNKNOWN\n"
            "MISSING_OR_INCORRECT: N/A\n"
            f"NOTE: Validation step failed ({e}); "
            "please review sources manually."
        )


# --------------------------------------------------------------------------
# Verdict parser
# --------------------------------------------------------------------------

def parse_verdict(validation_text: str) -> str:

    for line in validation_text.splitlines():

        if line.upper().startswith("VERDICT:"):

            return (
                line
                .split(":", 1)[1]
                .strip()
                .upper()
            )

    return "UNKNOWN"


def extract_validation_note(validation_text: str) -> str:

    for line in validation_text.splitlines():

        if line.upper().startswith("NOTE:"):

            return line.split(
                ":",
                1,
            )[1].strip()

    return ""


def extract_missing_claims(validation_text: str) -> str:

    for line in validation_text.splitlines():

        if line.upper().startswith(
            "MISSING_OR_INCORRECT:"
        ):

            return line.split(
                ":",
                1,
            )[1].strip()

    return "None"


# --------------------------------------------------------------------------
# Verdict configuration
# --------------------------------------------------------------------------

VERDICT_STYLE = {

    "SUPPORTED": {
        "icon": "✓",
        "class": "verdict-supported",
        "label": "Supported",
        "description": (
            "The answer is fully supported by the retrieved "
            "document evidence."
        ),
    },

    "PARTIALLY_SUPPORTED": {
        "icon": "◐",
        "class": "verdict-partial",
        "label": "Partially supported",
        "description": (
            "Some claims are supported, but one or more claims "
            "need additional evidence."
        ),
    },

    "NOT_SUPPORTED": {
        "icon": "✕",
        "class": "verdict-unsupported",
        "label": "Not supported",
        "description": (
            "The answer contains a claim that is not supported "
            "by the retrieved evidence."
        ),
    },

    "NOT_IN_DOCUMENT": {
        "icon": "i",
        "class": "verdict-notfound",
        "label": "Not in document",
        "description": (
            "The uploaded documents do not contain enough "
            "information to answer this question."
        ),
    },

    "UNKNOWN": {
        "icon": "?",
        "class": "verdict-unknown",
        "label": "Validation unavailable",
        "description": (
            "The validation step could not produce a reliable verdict."
        ),
    },
}


# --------------------------------------------------------------------------
# Streamlit Cloud safe frontend
# --------------------------------------------------------------------------

def inject_design_system():
    """
    Lightweight Streamlit CSS.
    The UI deliberately avoids large HTML layouts and JavaScript so that
    Streamlit Community Cloud does not expose markup as page content.
    """
    st.markdown(
        """
        <style>
        :root {
            --bg: #0b1118;
            --surface: #111923;
            --surface2: #151f2c;
            --border: #293545;
            --text: #f3f6f9;
            --muted: #9aa7b6;
            --teal: #2dd4bf;
            --green: #34d399;
            --amber: #fbbf24;
            --red: #f87171;
            --blue: #60a5fa;
        }

        .stApp {
            background: var(--bg);
        }

        .block-container {
            max-width: 1380px;
            padding-top: 2rem;
            padding-bottom: 3rem;
            padding-left: 2.5rem;
            padding-right: 2.5rem;
        }

        [data-testid="stSidebar"] {
            background: #0d141d;
        }

        [data-testid="stSidebar"] > div:first-child {
            padding-top: 1.5rem;
        }

        .app-title {
            font-family: Georgia, "Times New Roman", serif;
            font-size: 2.25rem;
            font-weight: 700;
            color: var(--text);
            line-height: 1.15;
            margin-bottom: 0.25rem;
        }

        .app-subtitle {
            color: var(--muted);
            font-size: 0.9rem;
            margin-bottom: 1.5rem;
        }

        .section-kicker {
            color: var(--teal);
            font-family: "Courier New", monospace;
            font-size: 0.72rem;
            font-weight: 700;
            letter-spacing: 0.08em;
            text-transform: uppercase;
            margin-top: 1.2rem;
            margin-bottom: 0.35rem;
        }

        .section-heading {
            color: var(--text);
            font-family: Georgia, "Times New Roman", serif;
            font-size: 1.45rem;
            font-weight: 700;
            margin-bottom: 0.25rem;
        }

        .section-copy {
            color: var(--muted);
            font-size: 0.86rem;
            line-height: 1.6;
            margin-bottom: 1rem;
        }

        .card {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 14px;
            padding: 1.15rem;
            margin-bottom: 1rem;
        }

        .metric-card {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 12px;
            padding: 1rem;
            min-height: 105px;
        }

        .metric-label {
            color: var(--muted);
            font-size: 0.72rem;
            margin-bottom: 0.45rem;
        }

        .metric-value {
            color: var(--text);
            font-family: Georgia, "Times New Roman", serif;
            font-size: 1.65rem;
            font-weight: 700;
        }

        .metric-note {
            color: var(--muted);
            font-size: 0.7rem;
            margin-top: 0.3rem;
        }

        .answer-card {
            background: #121c27;
            border: 1px solid #334253;
            border-left: 4px solid var(--teal);
            border-radius: 14px;
            padding: 1.25rem;
            margin-top: 0.5rem;
            margin-bottom: 1rem;
        }

        .answer-label {
            color: var(--teal);
            font-family: "Courier New", monospace;
            font-size: 0.7rem;
            font-weight: 700;
            letter-spacing: 0.08em;
            text-transform: uppercase;
            margin-bottom: 0.55rem;
        }

        .question-text {
            color: var(--text);
            font-family: Georgia, "Times New Roman", serif;
            font-size: 1.12rem;
            font-weight: 700;
            line-height: 1.45;
        }

        .source-card {
            background: var(--surface2);
            border: 1px solid var(--border);
            border-left: 3px solid var(--teal);
            border-radius: 0 10px 10px 0;
            padding: 0.9rem;
            margin-bottom: 0.65rem;
        }

        .source-title {
            color: var(--teal);
            font-family: "Courier New", monospace;
            font-size: 0.72rem;
            font-weight: 700;
            margin-bottom: 0.4rem;
        }

        .source-meta {
            color: var(--muted);
            font-size: 0.68rem;
            margin-top: 0.45rem;
        }

        .status-pill {
            border-radius: 999px;
            padding: 0.3rem 0.65rem;
            font-size: 0.7rem;
            font-weight: 700;
        }

        .footer-note {
            color: var(--muted);
            font-size: 0.68rem;
            border-top: 1px solid var(--border);
            padding-top: 1rem;
            margin-top: 2rem;
        }

        div[data-testid="stFileUploader"] {
            border: 1px dashed #3a4a5d;
            border-radius: 12px;
            padding: 0.35rem;
            background: rgba(255,255,255,0.015);
        }

        .stButton > button {
            border-radius: 9px;
            min-height: 42px;
            font-weight: 600;
        }

        textarea {
            border-radius: 10px !important;
        }

        @media (max-width: 800px) {
            .block-container {
                padding-left: 1rem;
                padding-right: 1rem;
            }

            .app-title {
                font-size: 1.8rem;
            }
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def safe(text: str) -> str:
    return html.escape(str(text))


def render_header(client_available: bool):
    st.markdown(
        '<div class="app-title">Contract Auditor</div>',
        unsafe_allow_html=True,
    )
    st.markdown(
        '<div class="app-subtitle">'
        'Multi-document compliance intelligence, grounded in your uploaded evidence.'
        '</div>',
        unsafe_allow_html=True,
    )

    if client_available:
        st.success("AI validation service is configured.", icon="✓")
    else:
        st.warning(
            "AI validation service needs configuration. Add GROQ_API_KEY to Streamlit secrets.",
            icon="!",
        )


def render_workflow(active_step: int = 1):
    labels = [
        "1. Document intake",
        "2. Semantic indexing",
        "3. Compliance query",
        "4. Validated answer",
    ]

    cols = st.columns(4)
    for i, label in enumerate(labels, start=1):
        with cols[i - 1]:
            if i <= active_step:
                st.success(label, icon="✓")
            else:
                st.caption(label)


def render_stats():
    store = st.session_state.vector_store
    num_docs = len(st.session_state.indexed_filenames)
    num_chunks = len(store.chunks)
    num_questions = len(st.session_state.history)

    supported = sum(
        1
        for item in st.session_state.history
        if item["verdict"] == "SUPPORTED"
    )

    validation_rate = (
        (supported / num_questions) * 100
        if num_questions
        else 0
    )

    metrics = [
        ("DOCUMENTS", num_docs, "Indexed evidence files"),
        ("CHUNKS", f"{num_chunks:,}", "Searchable text units"),
        ("QUESTIONS", num_questions, "Compliance questions"),
        ("SUPPORTED", f"{validation_rate:.0f}%", "Fully grounded answers"),
    ]

    cols = st.columns(4)
    for col, (label, value, note) in zip(cols, metrics):
        with col:
            st.markdown(
                f"""
                <div class="metric-card">
                    <div class="metric-label">{safe(label)}</div>
                    <div class="metric-value">{safe(value)}</div>
                    <div class="metric-note">{safe(note)}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )


def render_sidebar(embedder: SentenceTransformer):
    with st.sidebar:
        st.markdown("## Document Intake")
        st.caption(
            "Upload contracts, agreements, policies, or other PDF evidence."
        )

        uploaded_files = st.file_uploader(
            "PDF documents",
            type=["pdf"],
            accept_multiple_files=True,
            help="You can upload multiple PDF documents.",
        )

        if uploaded_files:
            st.caption(f"{len(uploaded_files)} document(s) selected")

            for file in uploaded_files:
                st.write(f"📄 {file.name}")

            if st.button(
                "Process & Index Documents",
                type="primary",
                use_container_width=True,
            ):
                start = time.time()
                progress = st.progress(0, text="Preparing documents...")

                try:
                    progress.progress(
                        15,
                        text="Extracting PDF text...",
                    )

                    chunks = chunk_documents(uploaded_files)

                    progress.progress(
                        50,
                        text="Creating searchable chunks...",
                    )

                    if chunks:
                        progress.progress(
                            70,
                            text="Generating semantic embeddings...",
                        )

                        store = build_vector_store(
                            chunks,
                            embedder,
                        )

                        progress.progress(
                            92,
                            text="Building evidence index...",
                        )

                        st.session_state.vector_store = store
                        st.session_state.indexed_filenames = list(
                            {
                                c.source_file
                                for c in chunks
                            }
                        )

                        elapsed = time.time() - start

                        progress.progress(
                            100,
                            text="Indexing complete",
                        )

                        st.success(
                            f"Indexed {len(chunks):,} chunks from "
                            f"{len(st.session_state.indexed_filenames)} "
                            f"document(s) in {elapsed:.1f}s."
                        )
                    else:
                        progress.empty()
                        st.error("No extractable text was found.")

                except Exception as e:
                    progress.empty()
                    st.error(f"Indexing failed: {e}")

        st.divider()

        if st.session_state.indexed_filenames:
            st.markdown("### Active Evidence Base")

            for fname in st.session_state.indexed_filenames:
                st.write(f"✓ {fname}")

            if st.button(
                "Clear Evidence Base",
                use_container_width=True,
            ):
                st.session_state.vector_store = VectorStore()
                st.session_state.indexed_filenames = []
                st.session_state.history = []
                st.rerun()

        st.divider()

        st.markdown("### System")
        st.caption("Semantic retrieval")
        st.caption("FAISS + Sentence Transformers")
        st.caption("Groq answer generation")
        st.caption("Corrective RAG validation")


def render_pipeline_status(
    retrieval_done=False,
    generation_done=False,
    validation_done=False,
):
    cols = st.columns(3)

    stages = [
        ("Evidence retrieval", retrieval_done),
        ("Grounded answer", generation_done),
        ("Corrective validation", validation_done),
    ]

    for col, (label, done) in zip(cols, stages):
        with col:
            if done:
                st.success(label, icon="✓")
            else:
                st.info(label, icon="○")


def render_verdict(verdict: str, note: str = ""):
    config = VERDICT_STYLE.get(
        verdict,
        VERDICT_STYLE["UNKNOWN"],
    )

    if verdict == "SUPPORTED":
        st.success(
            f"**{config['label']}**\n\n"
            f"{note or config['description']}",
            icon="✓",
        )
    elif verdict == "PARTIALLY_SUPPORTED":
        st.warning(
            f"**{config['label']}**\n\n"
            f"{note or config['description']}",
            icon="◐",
        )
    elif verdict == "NOT_SUPPORTED":
        st.error(
            f"**{config['label']}**\n\n"
            f"{note or config['description']}",
            icon="✕",
        )
    elif verdict == "NOT_IN_DOCUMENT":
        st.info(
            f"**{config['label']}**\n\n"
            f"{note or config['description']}",
            icon="i",
        )
    else:
        st.warning(
            f"**{config['label']}**\n\n"
            f"{note or config['description']}",
            icon="?",
        )


def render_sources(sources: List[Chunk]):
    st.markdown(
        f"### Evidence Exhibits ({len(sources)})"
    )

    for index, chunk in enumerate(sources, start=1):
        st.markdown(
            f"""
            <div class="source-card">
                <div class="source-title">
                    [{index}] {safe(chunk.source_file)}
                </div>
                <div>
                    {safe(chunk.text)}
                </div>
                <div class="source-meta">
                    Page {chunk.page_number} · Chunk {chunk.chunk_id}
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )


def render_answer_block(entry: dict):
    verdict = entry["verdict"]

    note = extract_validation_note(
        entry["validation_raw"]
    )

    missing = extract_missing_claims(
        entry["validation_raw"]
    )

    st.markdown(
        '<div class="answer-card">',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="answer-label">Compliance Analysis</div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        f'<div class="question-text">{safe(entry["question"])}</div>',
        unsafe_allow_html=True,
    )

    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown(entry["answer"])

    render_verdict(verdict, note)

    with st.expander("Review validation findings"):
        st.write(
            "The validation model compared the generated answer "
            "against the retrieved source context."
        )

        st.markdown("**Missing or incorrect claims**")
        st.info(missing)

        st.markdown("**Raw validation response**")
        st.code(
            entry["validation_raw"],
            language="text",
        )

    with st.expander(
        f"View source evidence ({len(entry['sources'])})"
    ):
        render_sources(entry["sources"])


def render_history():
    if not st.session_state.history:
        return

    with st.expander(
        f"Query history ({len(st.session_state.history)})"
    ):
        for item in st.session_state.history:
            config = VERDICT_STYLE.get(
                item["verdict"],
                VERDICT_STYLE["UNKNOWN"],
            )

            st.markdown(
                f"**{item['question']}**"
            )

            st.caption(
                f"{config['icon']} {config['label']} · "
                f"{len(item['sources'])} source(s)"
            )

            st.divider()


def render_main(
    client_available: bool,
    embedder: SentenceTransformer,
):
    render_header(client_available)

    render_workflow(
        active_step=4
        if not st.session_state.vector_store.is_empty()
        else 1
    )

    if st.session_state.vector_store.is_empty():
        st.markdown(
            """
            <div class="card">
                <div class="section-kicker">Evidence workspace</div>
                <div class="section-heading">
                    Your evidence workspace is empty
                </div>
                <div class="section-copy">
                    Upload one or more contract or policy PDFs from the
                    sidebar. The application will extract text, create
                    semantic embeddings, index the evidence with FAISS,
                    and make it available for grounded questions.
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        st.markdown("### How the analysis works")

        cols = st.columns(3)

        with cols[0]:
            st.info(
                "**01 · Retrieve**\n\n"
                "Relevant passages are retrieved from the uploaded documents."
            )

        with cols[1]:
            st.info(
                "**02 · Generate**\n\n"
                "The answer is generated from the retrieved document context."
            )

        with cols[2]:
            st.info(
                "**03 · Validate**\n\n"
                "A second model pass checks whether the answer is supported."
            )

        return

    render_stats()

    if not client_available:
        st.error(
            "GROQ_API_KEY is not configured. "
            "Add it to Streamlit secrets before submitting a question."
        )

    st.markdown(
        '<div class="section-kicker">01 · Compliance Query</div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="section-heading">Ask across your evidence base</div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        '<div class="section-copy">'
        'Ask about obligations, dates, penalties, termination, payment terms, '
        'security requirements, or differences across the uploaded documents.'
        '</div>',
        unsafe_allow_html=True,
    )

    question = st.text_area(
        "Compliance question",
        placeholder=(
            "Example: What is the termination notice period "
            "across all vendor contracts?"
        ),
        height=120,
        label_visibility="collapsed",
    )

    st.caption(
        "Tip: Ask about a specific clause, obligation, date, amount, "
        "party, or comparison."
    )

    st.markdown("**Suggested queries**")

    examples = [
        "What are the termination notice periods?",
        "Which contracts contain indemnification clauses?",
        "What payment deadlines are specified?",
        "Are there any data security obligations?",
    ]

    cols = st.columns(4)

    for col, example in zip(cols, examples):
        with col:
            if st.button(
                example,
                key=f"example_{example}",
                use_container_width=True,
            ):
                question = example

    ask_disabled = (
        not client_available
        or not question.strip()
    )

    if st.button(
        "Analyze with Evidence",
        type="primary",
        disabled=ask_disabled,
        use_container_width=True,
    ):
        try:
            client = get_groq_client()
        except RuntimeError as e:
            st.error(str(e))
            return

        with st.status(
            "Running compliance analysis...",
            expanded=True,
        ) as status:
            st.write("Searching the evidence base...")

            top_chunks = retrieve_top_chunks(
                question,
                st.session_state.vector_store,
                embedder,
            )

            if not top_chunks:
                status.update(
                    label="No relevant evidence found",
                    state="complete",
                )

                st.info(
                    "The indexed documents do not contain enough relevant "
                    "text for this question. This is an informational result, "
                    "not a system error."
                )
                return

            st.write(
                f"Retrieved {len(top_chunks)} relevant evidence chunks."
            )

            context = format_context(top_chunks)

            st.write("Generating a grounded answer...")

            try:
                draft_answer = generate_answer(
                    client,
                    question,
                    context,
                )
            except RuntimeError as e:
                status.update(
                    label="Answer generation failed",
                    state="error",
                )
                st.error(str(e))
                return

            st.write("Running Corrective RAG validation...")

            validation_raw = validate_answer(
                client,
                question,
                context,
                draft_answer,
            )

            verdict = parse_verdict(validation_raw)

            status.update(
                label="Analysis complete",
                state="complete",
            )

        entry = {
            "question": question,
            "answer": draft_answer,
            "validation_raw": validation_raw,
            "verdict": verdict,
            "sources": top_chunks,
        }

        st.session_state.history.insert(
            0,
            entry,
        )

    if st.session_state.history:
        st.divider()

        st.markdown(
            '<div class="section-kicker">02 · Review Results</div>',
            unsafe_allow_html=True,
        )

        st.markdown(
            '<div class="section-heading">Evidence-backed analysis</div>',
            unsafe_allow_html=True,
        )

        st.markdown(
            '<div class="section-copy">'
            'Review the generated answer, validation verdict, and evidence '
            'used to support the result.'
            '</div>',
            unsafe_allow_html=True,
        )

        for entry in st.session_state.history:
            render_answer_block(entry)

        render_history()

    st.markdown(
        '<div class="footer-note">'
        'Contract Auditor · Evidence-first compliance analysis · '
        'Supported · Partially supported · Not supported · Not in document'
        '</div>',
        unsafe_allow_html=True,
    )


# --------------------------------------------------------------------------
# Session state
# --------------------------------------------------------------------------

def init_session_state():
    if "vector_store" not in st.session_state:
        st.session_state.vector_store = VectorStore()

    if "indexed_filenames" not in st.session_state:
        st.session_state.indexed_filenames = []

    if "history" not in st.session_state:
        st.session_state.history = []


# --------------------------------------------------------------------------
# Application entry point
# --------------------------------------------------------------------------

def main():
    st.set_page_config(
        page_title="Contract Auditor",
        page_icon="⚖️",
        layout="wide",
        initial_sidebar_state="expanded",
    )

    inject_design_system()
    init_session_state()

    try:
        embedder = load_embedding_model()
    except Exception as e:
        st.error(f"Failed to load embedding model: {e}")
        logger.exception("Embedding model load failed")
        return

    client_available = bool(
        st.secrets.get(
            "GROQ_API_KEY",
            None,
        )
    )

    render_sidebar(embedder)

    render_main(
        client_available,
        embedder,
    )


if __name__ == "__main__":
    main()
