"""
Smart Multi-Document Compliance & Contract Auditor
===================================================

A Streamlit web app that lets legal/finance/compliance teams upload multiple
PDF contracts or policy documents, ask natural-language questions across all
of them, and get answers that are:
  1. Grounded strictly in the uploaded text (Retrieval-Augmented Generation)
  2. Cited back to the exact source paragraph and document
  3. Fact-checked by a second "Corrective RAG" validation pass before display

Pipeline:
  PDF(s) -> pypdf text extraction -> RecursiveCharacterTextSplitter chunks
        -> Sentence-Transformer embeddings -> FAISS vector index
        -> similarity search -> Groq LLM answer generation
        -> Groq LLM validation ("does the context actually support this?")
        -> Streamlit UI (answer + validation verdict + cited source chunks)

Author: Generated for the Smart Multi-Document Compliance & Contract Auditor project.
"""

import io
import logging
import time
from dataclasses import dataclass, field
from typing import List, Tuple

import numpy as np
import streamlit as st
from pypdf import PdfReader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# faiss-cpu and sentence-transformers are both heavy imports (they pull in
# numpy/torch). We import them at module load time since they're required
# for the app to function at all -- if either is missing, requirements.txt
# was not installed correctly, and we want a fast, clear failure.
try:
    import faiss
except ImportError as e:  # pragma: no cover
    raise ImportError(
        "faiss-cpu is not installed. Run: pip install faiss-cpu"
    ) from e

try:
    from sentence_transformers import SentenceTransformer
except ImportError as e:  # pragma: no cover
    raise ImportError(
        "sentence-transformers is not installed. Run: pip install sentence-transformers"
    ) from e

from groq import Groq

# --------------------------------------------------------------------------
# Logging setup
# --------------------------------------------------------------------------
# We log to stdout (captured by Streamlit Cloud's log viewer) so that
# ingestion/query errors are traceable without exposing stack traces to
# end users in the UI itself.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("contract_auditor")

# --------------------------------------------------------------------------
# Configuration constants
# --------------------------------------------------------------------------
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"   # small, fast, free, runs on CPU
GROQ_MODEL_NAME = "llama-3.3-70b-versatile"  # good accuracy/speed tradeoff on Groq's free tier
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
TOP_K_RESULTS = 5

SYSTEM_ANSWER_PROMPT = """You are a precise contract and compliance analysis assistant.
You must answer the user's question using ONLY the information contained in the
provided context chunks below. Each chunk is labeled with its source document
and page number.

Rules:
- Do NOT use any outside knowledge or assumptions.
- If the answer is not fully contained in the context, explicitly say what is
  missing rather than guessing.
- When you state a fact, mention which document/page it came from
  (e.g., "According to Vendor_Agreement.pdf, page 4...").
- Be concise and structured. Use bullet points for multiple clauses/terms.
"""

SYSTEM_VALIDATION_PROMPT = """You are a strict fact-checking auditor. You will be given:
1. A set of source context chunks (with document/page labels)
2. A question
3. A draft answer generated by another AI from that context

Your job is to verify the draft answer against the context ONLY. Respond in
this exact format:

VERDICT: SUPPORTED | PARTIALLY_SUPPORTED | NOT_SUPPORTED
MISSING_OR_INCORRECT: <list any claims in the answer that are not backed by
the context, or state "None" if the answer is fully grounded>
NOTE: <one short sentence summarizing your finding for the end user>

Be strict: if the answer references a clause, number, date, or obligation
that does not literally appear in the context, mark it as NOT_SUPPORTED or
PARTIALLY_SUPPORTED and explain why.
"""


# --------------------------------------------------------------------------
# Data structures
# --------------------------------------------------------------------------
@dataclass
class Chunk:
    """A single retrievable unit of text with citation metadata."""
    text: str
    source_file: str
    page_number: int
    chunk_id: int


@dataclass
class VectorStore:
    """In-memory FAISS index paired with the chunk metadata it represents."""
    index: "faiss.IndexFlatL2" = None
    chunks: List[Chunk] = field(default_factory=list)
    dimension: int = 0

    def is_empty(self) -> bool:
        return self.index is None or len(self.chunks) == 0


# --------------------------------------------------------------------------
# Cached resource loaders
# --------------------------------------------------------------------------
@st.cache_resource(show_spinner=False)
def load_embedding_model() -> SentenceTransformer:
    """Load the sentence-transformer embedding model once per session/process."""
    logger.info("Loading embedding model: %s", EMBEDDING_MODEL_NAME)
    return SentenceTransformer(EMBEDDING_MODEL_NAME)


def get_groq_client() -> Groq:
    """
    Build a Groq client using the API key from Streamlit secrets.

    Looking the key up from st.secrets means it is never hard-coded in the
    repo. Locally, place it in .streamlit/secrets.toml (gitignored). On
    Streamlit Community Cloud, set it via the app's Secrets Manager in the
    dashboard.
    """
    api_key = st.secrets.get("GROQ_API_KEY", None)
    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY not found in Streamlit secrets. "
            "Add it locally to .streamlit/secrets.toml or, on Streamlit "
            "Community Cloud, under App settings -> Secrets."
        )
    return Groq(api_key=api_key)


# --------------------------------------------------------------------------
# Step 1: PDF ingestion & text extraction
# --------------------------------------------------------------------------
def extract_text_by_page(file_bytes: bytes, filename: str) -> List[Tuple[int, str]]:
    """
    Extract text from a PDF, page by page, using pypdf.

    Returns a list of (page_number, page_text) tuples. Pages that fail to
    extract (e.g. scanned/image-only pages with no text layer) are logged
    and skipped rather than crashing the whole ingestion run.
    """
    pages = []
    try:
        reader = PdfReader(io.BytesIO(file_bytes))
        for i, page in enumerate(reader.pages, start=1):
            try:
                text = page.extract_text() or ""
                if text.strip():
                    pages.append((i, text))
                else:
                    logger.warning(
                        "No extractable text on page %d of %s (possibly scanned/image PDF).",
                        i, filename,
                    )
            except Exception as page_err:  # noqa: BLE001
                logger.error("Failed to extract page %d of %s: %s", i, filename, page_err)
    except Exception as e:  # noqa: BLE001
        logger.error("Failed to read PDF %s: %s", filename, e)
        raise ValueError(f"Could not read '{filename}'. Is it a valid PDF? ({e})") from e
    return pages


# --------------------------------------------------------------------------
# Step 2: Chunking
# --------------------------------------------------------------------------
def chunk_documents(uploaded_files) -> List[Chunk]:
    """
    Extract and chunk text from all uploaded PDFs.

    Uses RecursiveCharacterTextSplitter (1000 chars, 200 overlap) so that
    each chunk is small enough for accurate embedding/retrieval but still
    carries enough surrounding context to be readable as a standalone
    citation.
    """
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        separators=["\n\n", "\n", ". ", " ", ""],
    )

    all_chunks: List[Chunk] = []
    chunk_id_counter = 0

    for uploaded_file in uploaded_files:
        filename = uploaded_file.name
        try:
            file_bytes = uploaded_file.read()
            pages = extract_text_by_page(file_bytes, filename)

            if not pages:
                st.warning(
                    f"'{filename}' produced no extractable text. "
                    f"It may be a scanned/image-only PDF that needs OCR first."
                )
                continue

            for page_number, page_text in pages:
                page_chunks = splitter.split_text(page_text)
                for chunk_text in page_chunks:
                    all_chunks.append(
                        Chunk(
                            text=chunk_text,
                            source_file=filename,
                            page_number=page_number,
                            chunk_id=chunk_id_counter,
                        )
                    )
                    chunk_id_counter += 1

        except ValueError as ve:
            st.error(str(ve))
            logger.error("Skipping file %s due to error: %s", filename, ve)
        except Exception as e:  # noqa: BLE001
            st.error(f"Unexpected error processing '{filename}': {e}")
            logger.exception("Unexpected error processing %s", filename)

    logger.info("Chunked %d total chunks from %d file(s).", len(all_chunks), len(uploaded_files))
    return all_chunks


# --------------------------------------------------------------------------
# Step 3: Embedding generation & FAISS indexing
# --------------------------------------------------------------------------
def build_vector_store(chunks: List[Chunk], embedder: SentenceTransformer) -> VectorStore:
    """
    Embed every chunk and load the vectors into a flat L2 FAISS index.

    IndexFlatL2 does an exact (brute-force) search, which is perfectly fast
    for the chunk volumes typical of a handful of contracts (thousands of
    chunks), and keeps the code simple and dependency-light versus an
    approximate index.
    """
    if not chunks:
        return VectorStore()

    texts = [c.text for c in chunks]
    logger.info("Embedding %d chunks...", len(texts))
    embeddings = embedder.encode(
        texts,
        show_progress_bar=False,
        convert_to_numpy=True,
        normalize_embeddings=True,  # cosine similarity via normalized L2
    ).astype("float32")

    dimension = embeddings.shape[1]
    index = faiss.IndexFlatL2(dimension)
    index.add(embeddings)

    logger.info("FAISS index built with dimension %d.", dimension)
    return VectorStore(index=index, chunks=chunks, dimension=dimension)


# --------------------------------------------------------------------------
# Step 4: Retrieval
# --------------------------------------------------------------------------
def retrieve_top_chunks(
    query: str, store: VectorStore, embedder: SentenceTransformer, k: int = TOP_K_RESULTS
) -> List[Chunk]:
    """Embed the user query and return the top-k most similar chunks."""
    if store.is_empty():
        return []

    query_vec = embedder.encode(
        [query], convert_to_numpy=True, normalize_embeddings=True
    ).astype("float32")

    k = min(k, len(store.chunks))
    distances, indices = store.index.search(query_vec, k)

    results = []
    for idx in indices[0]:
        if 0 <= idx < len(store.chunks):
            results.append(store.chunks[idx])
    return results


def format_context(chunks: List[Chunk]) -> str:
    """Turn retrieved chunks into a labeled context block for the LLM prompt."""
    blocks = []
    for c in chunks:
        blocks.append(
            f"[Source: {c.source_file}, Page {c.page_number}]\n{c.text}"
        )
    return "\n\n---\n\n".join(blocks)


# --------------------------------------------------------------------------
# Step 5: Groq answer generation
# --------------------------------------------------------------------------
def generate_answer(client: Groq, question: str, context: str) -> str:
    """Call Groq's chat completion API to produce a grounded answer."""
    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL_NAME,
            messages=[
                {"role": "system", "content": SYSTEM_ANSWER_PROMPT},
                {
                    "role": "user",
                    "content": f"CONTEXT:\n{context}\n\nQUESTION:\n{question}",
                },
            ],
            temperature=0.1,
            max_tokens=1024,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:  # noqa: BLE001
        logger.exception("Groq answer generation failed")
        raise RuntimeError(f"Answer generation failed: {e}") from e


# --------------------------------------------------------------------------
# Step 6: Corrective RAG validation pass
# --------------------------------------------------------------------------
def validate_answer(client: Groq, question: str, context: str, draft_answer: str) -> str:
    """
    Second LLM call that checks the draft answer against the retrieved
    context only, and flags unsupported or missing claims. This is the
    "Corrective RAG" step that catches hallucinations before the user sees
    them.
    """
    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL_NAME,
            messages=[
                {"role": "system", "content": SYSTEM_VALIDATION_PROMPT},
                {
                    "role": "user",
                    "content": (
                        f"CONTEXT:\n{context}\n\n"
                        f"QUESTION:\n{question}\n\n"
                        f"DRAFT ANSWER:\n{draft_answer}"
                    ),
                },
            ],
            temperature=0.0,
            max_tokens=400,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:  # noqa: BLE001
        logger.exception("Groq validation call failed")
        # Validation failing should not block the user from seeing the
        # answer -- degrade gracefully with a clear note instead.
        return (
            "VERDICT: UNKNOWN\nMISSING_OR_INCORRECT: N/A\n"
            f"NOTE: Validation step failed ({e}); please review sources manually."
        )


def parse_verdict(validation_text: str) -> str:
    """Pull just the VERDICT line out of the validation response for badge display."""
    for line in validation_text.splitlines():
        if line.upper().startswith("VERDICT:"):
            return line.split(":", 1)[1].strip().upper()
    return "UNKNOWN"


VERDICT_STYLE = {
    "SUPPORTED": ("✅", "green"),
    "PARTIALLY_SUPPORTED": ("⚠️", "orange"),
    "NOT_SUPPORTED": ("❌", "red"),
    "UNKNOWN": ("❔", "gray"),
}


# --------------------------------------------------------------------------
# Streamlit UI
# --------------------------------------------------------------------------
def init_session_state():
    if "vector_store" not in st.session_state:
        st.session_state.vector_store = VectorStore()
    if "indexed_filenames" not in st.session_state:
        st.session_state.indexed_filenames = []
    if "history" not in st.session_state:
        st.session_state.history = []  # list of dicts: question/answer/verdict/sources


def render_sidebar(embedder: SentenceTransformer):
    with st.sidebar:
        st.header("📁 Upload Documents")
        uploaded_files = st.file_uploader(
            "Upload one or more PDF contracts / policies",
            type=["pdf"],
            accept_multiple_files=True,
        )

        if uploaded_files and st.button("Process & Index Documents", type="primary"):
            with st.spinner("Extracting text, chunking, and building vector index..."):
                start = time.time()
                chunks = chunk_documents(uploaded_files)
                if chunks:
                    store = build_vector_store(chunks, embedder)
                    st.session_state.vector_store = store
                    st.session_state.indexed_filenames = list(
                        {c.source_file for c in chunks}
                    )
                    elapsed = time.time() - start
                    st.success(
                        f"Indexed {len(chunks)} chunks from "
                        f"{len(st.session_state.indexed_filenames)} document(s) "
                        f"in {elapsed:.1f}s."
                    )
                else:
                    st.error("No text could be extracted from the uploaded file(s).")

        if st.session_state.indexed_filenames:
            st.markdown("**Currently indexed:**")
            for fname in st.session_state.indexed_filenames:
                st.markdown(f"- {fname}")

            if st.button("Clear index"):
                st.session_state.vector_store = VectorStore()
                st.session_state.indexed_filenames = []
                st.session_state.history = []
                st.rerun()

        st.markdown("---")
        st.caption(
            "Retrieval: FAISS + Sentence-Transformers | "
            "Generation & validation: Groq API"
        )


def render_answer_block(entry: dict):
    """Render one Q&A turn: answer, validation badge, and cited sources."""
    st.markdown(f"### ❓ {entry['question']}")
    st.markdown(entry["answer"])

    icon, color = VERDICT_STYLE.get(entry["verdict"], VERDICT_STYLE["UNKNOWN"])
    st.markdown(
        f"**Validation:** :{color}[{icon} {entry['verdict'].replace('_', ' ').title()}]"
    )
    with st.expander("Show fact-check details"):
        st.text(entry["validation_raw"])

    with st.expander(f"📎 Show {len(entry['sources'])} cited source chunk(s)"):
        for c in entry["sources"]:
            st.markdown(f"**{c.source_file} — page {c.page_number}**")
            st.info(c.text)


def render_main(client_available: bool, embedder: SentenceTransformer):
    st.title("📑 Smart Multi-Document Compliance & Contract Auditor")
    st.caption(
        "Upload contracts or policy PDFs on the left, then ask questions. "
        "Every answer is grounded in your documents and independently fact-checked."
    )

    if not client_available:
        st.error(
            "GROQ_API_KEY is not configured. Add it to `.streamlit/secrets.toml` "
            "(local) or the Streamlit Cloud Secrets Manager (deployed) before "
            "asking questions."
        )

    if st.session_state.vector_store.is_empty():
        st.info("👈 Upload and index at least one PDF to get started.")
        return

    question = st.text_area(
        "Ask a question about the uploaded document(s)",
        placeholder="e.g. What is the termination notice period across all vendor contracts?",
        height=80,
    )

    ask_disabled = not client_available or not question.strip()
    if st.button("Get Answer", type="primary", disabled=ask_disabled):
        try:
            client = get_groq_client()
        except RuntimeError as e:
            st.error(str(e))
            return

        with st.spinner("Retrieving relevant clauses..."):
            top_chunks = retrieve_top_chunks(question, st.session_state.vector_store, embedder)

        if not top_chunks:
            st.warning("No relevant content found in the indexed documents for this question.")
            return

        context = format_context(top_chunks)

        with st.spinner("Generating grounded answer via Groq..."):
            try:
                draft_answer = generate_answer(client, question, context)
            except RuntimeError as e:
                st.error(str(e))
                return

        with st.spinner("Running Corrective RAG validation..."):
            validation_raw = validate_answer(client, question, context, draft_answer)
            verdict = parse_verdict(validation_raw)

        entry = {
            "question": question,
            "answer": draft_answer,
            "validation_raw": validation_raw,
            "verdict": verdict,
            "sources": top_chunks,
        }
        st.session_state.history.insert(0, entry)

    st.markdown("---")
    for entry in st.session_state.history:
        render_answer_block(entry)
        st.markdown("---")


def main():
    st.set_page_config(
        page_title="Smart Contract Auditor",
        page_icon="📑",
        layout="wide",
    )
    init_session_state()

    try:
        embedder = load_embedding_model()
    except Exception as e:  # noqa: BLE001
        st.error(f"Failed to load embedding model: {e}")
        logger.exception("Embedding model load failed")
        return

    client_available = bool(st.secrets.get("GROQ_API_KEY", None))

    render_sidebar(embedder)
    render_main(client_available, embedder)


if __name__ == "__main__":
    main()
