"""
Smart Multi-Document Compliance & Contract Auditor
===================================================

A Streamlit web app that lets legal/finance/compliance teams upload multiple
PDF contracts or policy documents, ask natural-language questions across all
of them, and get answers that are:
  1. Grounded strictly in the uploaded text (Retrieval-Augmented Generation)
  2. Cited back to the exact source paragraph and document
  3. Fact-checked by a second "Corrective RAG" validation pass before display

Pipeline:
  PDF(s) -> pypdf text extraction -> RecursiveCharacterTextSplitter chunks
        -> Sentence-Transformer embeddings -> FAISS vector index
        -> similarity search -> Groq LLM answer generation
        -> Groq LLM validation ("does the context actually support this?")
        -> Streamlit UI (answer + validation verdict + cited source chunks)

Author: Generated for the Smart Multi-Document Compliance & Contract Auditor project.
"""

import html
import io
import logging
import time
from dataclasses import dataclass, field
from typing import List, Tuple

import numpy as np
import streamlit as st
from pypdf import PdfReader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# faiss-cpu and sentence-transformers are both heavy imports (they pull in
# numpy/torch). We import them at module load time since they're required
# for the app to function at all -- if either is missing, requirements.txt
# was not installed correctly, and we want a fast, clear failure.
try:
    import faiss
except ImportError as e:  # pragma: no cover
    raise ImportError(
        "faiss-cpu is not installed. Run: pip install faiss-cpu"
    ) from e

try:
    from sentence_transformers import SentenceTransformer
except ImportError as e:  # pragma: no cover
    raise ImportError(
        "sentence-transformers is not installed. Run: pip install sentence-transformers"
    ) from e

from groq import Groq

# --------------------------------------------------------------------------
# Logging setup
# --------------------------------------------------------------------------
# We log to stdout (captured by Streamlit Cloud's log viewer) so that
# ingestion/query errors are traceable without exposing stack traces to
# end users in the UI itself.
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("contract_auditor")

# --------------------------------------------------------------------------
# Configuration constants
# --------------------------------------------------------------------------
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"   # small, fast, free, runs on CPU
GROQ_MODEL_NAME = "openai/gpt-oss-120b"  # available on Groq's free/developer tier as of Sep 2026
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
TOP_K_RESULTS = 5

SYSTEM_ANSWER_PROMPT = """You are a precise contract and compliance analysis assistant.
You must answer the user's question using ONLY the information contained in the
provided context chunks below. Each chunk is labeled with its source document
and page number.

Rules:
- Do NOT use any outside knowledge or assumptions.
- If the answer is not fully contained in the context, explicitly say what is
  missing rather than guessing.
- When you state a fact, mention which document/page it came from
  (e.g., "According to Vendor_Agreement.pdf, page 4...").
- Be concise and structured. Use bullet points for multiple clauses/terms.
"""

SYSTEM_VALIDATION_PROMPT = """You are a strict fact-checking auditor. You will be given:
1. A set of source context chunks (with document/page labels)
2. A question
3. A draft answer generated by another AI from that context

Your job is to verify the draft answer against the context ONLY. Respond in
this exact format:

VERDICT: SUPPORTED | PARTIALLY_SUPPORTED | NOT_SUPPORTED | NOT_IN_DOCUMENT
MISSING_OR_INCORRECT: <list any claims in the answer that are not backed by
the context, or state "None" if the answer is fully grounded>
NOTE: <one short sentence summarizing your finding for the end user>

Verdict definitions:
- SUPPORTED: every factual claim in the answer is explicitly backed by the context.
- PARTIALLY_SUPPORTED: some claims are backed, others are not.
- NOT_SUPPORTED: the answer states a clause, number, date, or obligation that
  does NOT appear in the context (a likely hallucination). This is the
  category for genuinely fabricated content.
- NOT_IN_DOCUMENT: the context simply does not address the topic asked about,
  and the answer correctly says so instead of inventing an answer. This is a
  GOOD outcome, not a hallucination -- use this verdict instead of
  NOT_SUPPORTED whenever the answer honestly reports an absence of relevant
  information rather than fabricating one.

Be strict: only use NOT_SUPPORTED when the answer asserts something as fact
that contradicts or is absent from the context. An honest "not found" answer
should be NOT_IN_DOCUMENT, never NOT_SUPPORTED.
"""


# --------------------------------------------------------------------------
# Data structures
# --------------------------------------------------------------------------
@dataclass
class Chunk:
    """A single retrievable unit of text with citation metadata."""
    text: str
    source_file: str
    page_number: int
    chunk_id: int


@dataclass
class VectorStore:
    """In-memory FAISS index paired with the chunk metadata it represents."""
    index: "faiss.IndexFlatL2" = None
    chunks: List[Chunk] = field(default_factory=list)
    dimension: int = 0

    def is_empty(self) -> bool:
        return self.index is None or len(self.chunks) == 0


# --------------------------------------------------------------------------
# Cached resource loaders
# --------------------------------------------------------------------------
@st.cache_resource(show_spinner=False)
def load_embedding_model() -> SentenceTransformer:
    """Load the sentence-transformer embedding model once per session/process."""
    logger.info("Loading embedding model: %s", EMBEDDING_MODEL_NAME)
    return SentenceTransformer(EMBEDDING_MODEL_NAME)


def get_groq_client() -> Groq:
    """
    Build a Groq client using the API key from Streamlit secrets.

    Looking the key up from st.secrets means it is never hard-coded in the
    repo. Locally, place it in .streamlit/secrets.toml (gitignored). On
    Streamlit Community Cloud, set it via the app's Secrets Manager in the
    dashboard.
    """
    api_key = st.secrets.get("GROQ_API_KEY", None)
    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY not found in Streamlit secrets. "
            "Add it locally to .streamlit/secrets.toml or, on Streamlit "
            "Community Cloud, under App settings -> Secrets."
        )
    return Groq(api_key=api_key)


# --------------------------------------------------------------------------
# Step 1: PDF ingestion & text extraction
# --------------------------------------------------------------------------
def extract_text_by_page(file_bytes: bytes, filename: str) -> List[Tuple[int, str]]:
    """
    Extract text from a PDF, page by page, using pypdf.

    Returns a list of (page_number, page_text) tuples. Pages that fail to
    extract (e.g. scanned/image-only pages with no text layer) are logged
    and skipped rather than crashing the whole ingestion run.
    """
    pages = []
    try:
        reader = PdfReader(io.BytesIO(file_bytes))
        for i, page in enumerate(reader.pages, start=1):
            try:
                text = page.extract_text() or ""
                if text.strip():
                    pages.append((i, text))
                else:
                    logger.warning(
                        "No extractable text on page %d of %s (possibly scanned/image PDF).",
                        i, filename,
                    )
            except Exception as page_err:  # noqa: BLE001
                logger.error("Failed to extract page %d of %s: %s", i, filename, page_err)
    except Exception as e:  # noqa: BLE001
        logger.error("Failed to read PDF %s: %s", filename, e)
        raise ValueError(f"Could not read '{filename}'. Is it a valid PDF? ({e})") from e
    return pages


# --------------------------------------------------------------------------
# Step 2: Chunking
# --------------------------------------------------------------------------
def chunk_documents(uploaded_files) -> List[Chunk]:
    """
    Extract and chunk text from all uploaded PDFs.

    Uses RecursiveCharacterTextSplitter (1000 chars, 200 overlap) so that
    each chunk is small enough for accurate embedding/retrieval but still
    carries enough surrounding context to be readable as a standalone
    citation.
    """
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        separators=["\n\n", "\n", ". ", " ", ""],
    )

    all_chunks: List[Chunk] = []
    chunk_id_counter = 0

    for uploaded_file in uploaded_files:
        filename = uploaded_file.name
        try:
            file_bytes = uploaded_file.read()
            pages = extract_text_by_page(file_bytes, filename)

            if not pages:
                st.warning(
                    f"'{filename}' produced no extractable text. "
                    f"It may be a scanned/image-only PDF that needs OCR first."
                )
                continue

            for page_number, page_text in pages:
                page_chunks = splitter.split_text(page_text)
                for chunk_text in page_chunks:
                    all_chunks.append(
                        Chunk(
                            text=chunk_text,
                            source_file=filename,
                            page_number=page_number,
                            chunk_id=chunk_id_counter,
                        )
                    )
                    chunk_id_counter += 1

        except ValueError as ve:
            st.error(str(ve))
            logger.error("Skipping file %s due to error: %s", filename, ve)
        except Exception as e:  # noqa: BLE001
            st.error(f"Unexpected error processing '{filename}': {e}")
            logger.exception("Unexpected error processing %s", filename)

    logger.info("Chunked %d total chunks from %d file(s).", len(all_chunks), len(uploaded_files))
    return all_chunks


# --------------------------------------------------------------------------
# Step 3: Embedding generation & FAISS indexing
# --------------------------------------------------------------------------
def build_vector_store(chunks: List[Chunk], embedder: SentenceTransformer) -> VectorStore:
    """
    Embed every chunk and load the vectors into a flat L2 FAISS index.

    IndexFlatL2 does an exact (brute-force) search, which is perfectly fast
    for the chunk volumes typical of a handful of contracts (thousands of
    chunks), and keeps the code simple and dependency-light versus an
    approximate index.
    """
    if not chunks:
        return VectorStore()

    texts = [c.text for c in chunks]
    logger.info("Embedding %d chunks...", len(texts))
    embeddings = embedder.encode(
        texts,
        show_progress_bar=False,
        convert_to_numpy=True,
        normalize_embeddings=True,  # cosine similarity via normalized L2
    ).astype("float32")

    dimension = embeddings.shape[1]
    index = faiss.IndexFlatL2(dimension)
    index.add(embeddings)

    logger.info("FAISS index built with dimension %d.", dimension)
    return VectorStore(index=index, chunks=chunks, dimension=dimension)


# --------------------------------------------------------------------------
# Step 4: Retrieval
# --------------------------------------------------------------------------
def retrieve_top_chunks(
    query: str, store: VectorStore, embedder: SentenceTransformer, k: int = TOP_K_RESULTS
) -> List[Chunk]:
    """Embed the user query and return the top-k most similar chunks."""
    if store.is_empty():
        return []

    query_vec = embedder.encode(
        [query], convert_to_numpy=True, normalize_embeddings=True
    ).astype("float32")

    k = min(k, len(store.chunks))
    distances, indices = store.index.search(query_vec, k)

    results = []
    for idx in indices[0]:
        if 0 <= idx < len(store.chunks):
            results.append(store.chunks[idx])
    return results


def format_context(chunks: List[Chunk]) -> str:
    """Turn retrieved chunks into a labeled context block for the LLM prompt."""
    blocks = []
    for c in chunks:
        blocks.append(
            f"[Source: {c.source_file}, Page {c.page_number}]\n{c.text}"
        )
    return "\n\n---\n\n".join(blocks)


# --------------------------------------------------------------------------
# Step 5: Groq answer generation
# --------------------------------------------------------------------------
def generate_answer(client: Groq, question: str, context: str) -> str:
    """Call Groq's chat completion API to produce a grounded answer."""
    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL_NAME,
            messages=[
                {"role": "system", "content": SYSTEM_ANSWER_PROMPT},
                {
                    "role": "user",
                    "content": f"CONTEXT:\n{context}\n\nQUESTION:\n{question}",
                },
            ],
            temperature=0.1,
            max_tokens=1024,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:  # noqa: BLE001
        logger.exception("Groq answer generation failed")
        raise RuntimeError(f"Answer generation failed: {e}") from e


# --------------------------------------------------------------------------
# Step 6: Corrective RAG validation pass
# --------------------------------------------------------------------------
def validate_answer(client: Groq, question: str, context: str, draft_answer: str) -> str:
    """
    Second LLM call that checks the draft answer against the retrieved
    context only, and flags unsupported or missing claims. This is the
    "Corrective RAG" step that catches hallucinations before the user sees
    them.
    """
    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL_NAME,
            messages=[
                {"role": "system", "content": SYSTEM_VALIDATION_PROMPT},
                {
                    "role": "user",
                    "content": (
                        f"CONTEXT:\n{context}\n\n"
                        f"QUESTION:\n{question}\n\n"
                        f"DRAFT ANSWER:\n{draft_answer}"
                    ),
                },
            ],
            temperature=0.0,
            max_tokens=400,
        )
        return response.choices[0].message.content.strip()
    except Exception as e:  # noqa: BLE001
        logger.exception("Groq validation call failed")
        # Validation failing should not block the user from seeing the
        # answer -- degrade gracefully with a clear note instead.
        return (
            "VERDICT: UNKNOWN\nMISSING_OR_INCORRECT: N/A\n"
            f"NOTE: Validation step failed ({e}); please review sources manually."
        )


def parse_verdict(validation_text: str) -> str:
    """Pull just the VERDICT line out of the validation response for badge display."""
    for line in validation_text.splitlines():
        if line.upper().startswith("VERDICT:"):
            return line.split(":", 1)[1].strip().upper()
    return "UNKNOWN"


VERDICT_STYLE = {
    # verdict -> (icon, hex background color, human label)
    "SUPPORTED": ("✓", "#15803D", "Supported"),
    "PARTIALLY_SUPPORTED": ("~", "#92400E", "Partially supported"),
    "NOT_SUPPORTED": ("✕", "#B91C1C", "Not supported"),
    "NOT_IN_DOCUMENT": ("–", "#1D4ED8", "Not in document"),
    "UNKNOWN": ("?", "#4B5563", "Unknown"),
}


# --------------------------------------------------------------------------
# Design system: "Slate & Teal" -- dark theme.
#
# The actual dark/light mode and all native widget coloring (buttons,
# inputs, file uploader, alerts, expanders) is handled by
# .streamlit/config.toml -- Streamlit's own theming engine, which is built
# to guarantee correct contrast for its own components. We deliberately do
# NOT hand-roll CSS overrides for native widgets here, because blindly
# forcing a text color onto every descendant of a container risks landing
# on an element that keeps its own background regardless of the parent
# (e.g. an inner white chip), producing invisible text. Instead, we only
# add colors/backgrounds to the custom HTML blocks we build ourselves below
# (header, docket bar, memo blocks, verdict pills, exhibits), where we also
# control the background and can guarantee the pairing is readable.
# --------------------------------------------------------------------------
def inject_design_system():
    st.markdown(
        """
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@500;600;700&family=Inter:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap');

        :root {
            --ink: #E7EAF0;          /* primary text -- light, for our own dark surfaces */
            --ink-soft: #9AA3B2;     /* secondary text -- still >4.5:1 on dark surfaces */
            --surface: #1B212C;      /* memo blocks, docket bar -- one step lighter than page bg */
            --surface-dim: #242C3A;  /* exhibits -- another step lighter, for nesting inside memo */
            --accent: #14B8A6;       /* teal -- borders, labels, links on dark surfaces */
            --accent-dark: #0F766E;  /* deeper teal -- matches primaryColor in config.toml */
            --line: #2E3646;         /* hairline borders on dark surfaces */
        }

        html, body, [class*="css"] {
            font-family: 'Inter', sans-serif;
        }

        /* ---- Header ---- */
        .auditor-header {
            display: flex;
            align-items: baseline;
            gap: 16px;
            padding-bottom: 16px;
            margin-bottom: 4px;
            border-bottom: 2px solid var(--line);
            flex-wrap: wrap;
        }
        .auditor-header .mark {
            font-family: 'Source Serif 4', serif;
            font-weight: 700;
            font-size: 2.05rem;
            color: var(--ink);
            letter-spacing: -0.01em;
        }
        .auditor-header .tagline {
            font-size: 0.95rem;
            color: var(--ink-soft);
        }

        /* ---- Docket / stats bar ---- */
        .docket-bar {
            display: flex;
            gap: 32px;
            padding: 16px 20px;
            background: var(--surface);
            border: 1px solid var(--line);
            border-radius: 6px;
            margin-bottom: 22px;
        }
        .docket-stat .num {
            font-family: 'Source Serif 4', serif;
            font-size: 1.5rem;
            font-weight: 600;
            color: var(--ink);
            line-height: 1.1;
        }
        .docket-stat .label {
            font-size: 0.78rem;
            color: var(--ink-soft);
        }

        /* ---- Memo (answer) block ---- */
        .memo-block {
            background: var(--surface);
            border: 1px solid var(--line);
            border-left: 4px solid var(--accent);
            border-radius: 0 6px 6px 0;
            padding: 20px 24px 6px 24px;
            margin-bottom: 4px;
        }
        .memo-block p, .memo-block li, .memo-block strong {
            color: var(--ink) !important;
        }
        .memo-question {
            font-family: 'Source Serif 4', serif;
            font-size: 1.2rem;
            font-weight: 600;
            color: var(--ink);
            margin-bottom: 12px;
            line-height: 1.4;
        }

        /* ---- Verdict pill: white text on a solid, tested-dark color ---- */
        .verdict-row {
            display: flex;
            align-items: center;
            gap: 10px;
            margin: 14px 0 4px 0;
        }
        .verdict-pill {
            display: inline-flex;
            align-items: center;
            gap: 7px;
            padding: 4px 12px;
            border-radius: 4px;
            font-family: 'IBM Plex Mono', monospace;
            font-size: 0.76rem;
            font-weight: 500;
            color: #FFFFFF;
            letter-spacing: 0.02em;
        }
        .verdict-caption {
            font-size: 0.82rem;
            color: var(--ink-soft);
        }

        /* ---- Exhibit (source citation) ---- */
        .exhibit {
            border: 1px solid var(--line);
            border-left: 3px solid var(--accent);
            border-radius: 0 6px 6px 0;
            padding: 10px 16px;
            margin: 10px 0;
            background: var(--surface-dim);
        }
        .exhibit-label {
            font-family: 'IBM Plex Mono', monospace;
            font-size: 0.74rem;
            color: var(--accent);
            margin-bottom: 5px;
            font-weight: 600;
        }
        .exhibit-text {
            font-size: 0.92rem;
            color: var(--ink);
            line-height: 1.55;
        }

        /* ---- Section divider ---- */
        .ledger-rule {
            border: none;
            border-top: 1px solid var(--line);
            margin: 28px 0;
        }

        /* ---- Expander: font only, no color override -- config.toml already
               guarantees correct expander text contrast in dark mode ---- */
        .streamlit-expanderHeader {
            font-family: 'IBM Plex Mono', monospace !important;
            font-size: 0.82rem !important;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def render_verdict_pill(verdict: str, note: str = "") -> str:
    """Build the HTML for a verdict pill + optional trailing caption."""
    icon, color, label = VERDICT_STYLE.get(verdict, VERDICT_STYLE["UNKNOWN"])
    caption = f'<span class="verdict-caption">{html.escape(note)}</span>' if note else ""
    return (
        f'<div class="verdict-row">'
        f'<span class="verdict-pill" style="background:{color};">{icon} VERDICT: {verdict}</span>'
        f'{caption}'
        f'</div>'
    )


# --------------------------------------------------------------------------
# Streamlit UI
# --------------------------------------------------------------------------
def init_session_state():
    if "vector_store" not in st.session_state:
        st.session_state.vector_store = VectorStore()
    if "indexed_filenames" not in st.session_state:
        st.session_state.indexed_filenames = []
    if "history" not in st.session_state:
        st.session_state.history = []  # list of dicts: question/answer/verdict/sources


def render_sidebar(embedder: SentenceTransformer):
    with st.sidebar:
        st.markdown(
            '<div style="font-family:\'Source Serif 4\',serif; font-weight:600; '
            'font-size:1.15rem; color:var(--ink); margin-bottom:2px;">Document Intake</div>'
            '<div style="font-size:0.82rem; color:var(--ink-soft); margin-bottom:16px;">'
            '1. Upload &nbsp;→&nbsp; 2. Index &nbsp;→&nbsp; 3. Ask</div>',
            unsafe_allow_html=True,
        )
        uploaded_files = st.file_uploader(
            "PDF contracts or policies",
            type=["pdf"],
            accept_multiple_files=True,
            label_visibility="collapsed",
        )

        if uploaded_files and st.button("Process & Index Documents", type="primary"):
            with st.spinner("Extracting text, chunking, and building vector index..."):
                start = time.time()
                chunks = chunk_documents(uploaded_files)
                if chunks:
                    store = build_vector_store(chunks, embedder)
                    st.session_state.vector_store = store
                    st.session_state.indexed_filenames = list(
                        {c.source_file for c in chunks}
                    )
                    elapsed = time.time() - start
                    st.success(
                        f"Indexed {len(chunks)} chunks from "
                        f"{len(st.session_state.indexed_filenames)} document(s) "
                        f"in {elapsed:.1f}s."
                    )
                else:
                    st.error("No text could be extracted from the uploaded file(s).")

        if st.session_state.indexed_filenames:
            st.markdown(
                '<div style="font-size:0.82rem; color:var(--ink-soft); '
                'margin-top:18px; margin-bottom:4px;">On the record</div>',
                unsafe_allow_html=True,
            )
            for fname in st.session_state.indexed_filenames:
                st.markdown(
                    f'<div style="font-family:\'IBM Plex Mono\',monospace; font-size:0.8rem; '
                    f'color:var(--ink); padding:4px 0; border-bottom:1px solid var(--line);">'
                    f'{html.escape(fname)}</div>',
                    unsafe_allow_html=True,
                )

            if st.button("Clear index"):
                st.session_state.vector_store = VectorStore()
                st.session_state.indexed_filenames = []
                st.session_state.history = []
                st.rerun()

        st.markdown("<hr/>", unsafe_allow_html=True)
        st.markdown(
            '<div style="font-size:0.75rem; color:var(--ink-soft); line-height:1.6;">'
            'Retrieval — FAISS + Sentence-Transformers<br/>'
            'Generation &amp; validation — Groq API</div>',
            unsafe_allow_html=True,
        )


def render_answer_block(entry: dict):
    """Render one Q&A turn: answer, validation badge, and cited sources."""
    st.markdown(
        f'<div class="memo-block">'
        f'<div class="memo-question">{html.escape(entry["question"])}</div>',
        unsafe_allow_html=True,
    )
    st.markdown(entry["answer"])
    st.markdown(render_verdict_pill(entry["verdict"]), unsafe_allow_html=True)
    st.markdown("</div>", unsafe_allow_html=True)

    with st.expander("Fact-check details"):
        st.text(entry["validation_raw"])

    with st.expander(f"Cited sources ({len(entry['sources'])})"):
        for c in entry["sources"]:
            st.markdown(
                f'<div class="exhibit">'
                f'<div class="exhibit-label">{html.escape(c.source_file)} · page {c.page_number}</div>'
                f'<div class="exhibit-text">{html.escape(c.text)}</div>'
                f'</div>',
                unsafe_allow_html=True,
            )
    st.markdown('<hr class="ledger-rule"/>', unsafe_allow_html=True)


def render_main(client_available: bool, embedder: SentenceTransformer):
    st.markdown(
        '<div class="auditor-header">'
        '<span class="mark">Contract Auditor</span>'
        '<span class="tagline">Grounded answers, cited to the page, fact-checked before you see them.</span>'
        '</div>',
        unsafe_allow_html=True,
    )

    if not st.session_state.vector_store.is_empty():
        num_docs = len(st.session_state.indexed_filenames)
        num_chunks = len(st.session_state.vector_store.chunks)
        num_questions = len(st.session_state.history)
        st.markdown(
            '<div class="docket-bar">'
            f'<div class="docket-stat"><div class="num">{num_docs}</div>'
            f'<div class="label">Document{"s" if num_docs != 1 else ""} indexed</div></div>'
            f'<div class="docket-stat"><div class="num">{num_chunks}</div>'
            f'<div class="label">Searchable chunks</div></div>'
            f'<div class="docket-stat"><div class="num">{num_questions}</div>'
            f'<div class="label">Question{"s" if num_questions != 1 else ""} asked</div></div>'
            '</div>',
            unsafe_allow_html=True,
        )

    if not client_available:
        st.error(
            "GROQ_API_KEY is not configured. Add it to `.streamlit/secrets.toml` "
            "(local) or the Streamlit Cloud Secrets Manager (deployed) before "
            "asking questions."
        )

    if st.session_state.vector_store.is_empty():
        st.markdown(
            '<div style="border-left:4px solid var(--line); background:var(--surface); '
            'padding:20px 24px; color:var(--ink-soft); font-size:0.95rem;">'
            'No documents on file yet. Upload one or more PDFs in the sidebar '
            'and click <strong>Process &amp; Index Documents</strong> to begin.'
            '</div>',
            unsafe_allow_html=True,
        )
        return

    question = st.text_area(
        "Ask a question about the uploaded document(s)",
        placeholder="e.g. What is the termination notice period across all vendor contracts?",
        height=80,
    )

    ask_disabled = not client_available or not question.strip()
    if st.button("Get Answer", type="primary", disabled=ask_disabled):
        try:
            client = get_groq_client()
        except RuntimeError as e:
            st.error(str(e))
            return

        with st.spinner("Retrieving relevant clauses..."):
            top_chunks = retrieve_top_chunks(question, st.session_state.vector_store, embedder)

        if not top_chunks:
            st.warning("No relevant content found in the indexed documents for this question.")
            return

        context = format_context(top_chunks)

        with st.spinner("Generating grounded answer via Groq..."):
            try:
                draft_answer = generate_answer(client, question, context)
            except RuntimeError as e:
                st.error(str(e))
                return

        with st.spinner("Running Corrective RAG validation..."):
            validation_raw = validate_answer(client, question, context, draft_answer)
            verdict = parse_verdict(validation_raw)

        entry = {
            "question": question,
            "answer": draft_answer,
            "validation_raw": validation_raw,
            "verdict": verdict,
            "sources": top_chunks,
        }
        st.session_state.history.insert(0, entry)

    st.markdown('<hr class="ledger-rule"/>', unsafe_allow_html=True)
    for entry in st.session_state.history:
        render_answer_block(entry)


def main():
    st.set_page_config(
        page_title="Contract Auditor",
        page_icon="⚖️",
        layout="wide",
    )
    inject_design_system()
    init_session_state()

    try:
        embedder = load_embedding_model()
    except Exception as e:  # noqa: BLE001
        st.error(f"Failed to load embedding model: {e}")
        logger.exception("Embedding model load failed")
        return

    client_available = bool(st.secrets.get("GROQ_API_KEY", None))

    render_sidebar(embedder)
    render_main(client_available, embedder)


if __name__ == "__main__":
    main()
